name: qscondominio
description: git remote add origin

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ">=4.0.6 <6.0.0"
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  mocktail: ^0.3.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
