name: ci-pr

on:

  pull_request:
    branches:
      - 'dev'
      - 'main'
  workflow_call: 

    


# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Check bash
        run: | 
          echo $0  
          which bash   
      - name: Flutter version
        run: flutter --version                     
      - name: Run Lint
        run: flutter analyze --no-pub | grep -v 'TODO:'
      - name: Run tests with coverage
        run: flutter test --coverage
      - name: Verify test coverage
        run: |
          flutter pub global activate very_good_cli 
          very_good test -j 1 --optimization --coverage
      - name: 📊 Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 80    