name: ci-push

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'


# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    check-branch-name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get origin branch name
    run: echo "::set-output name=origin_branch::$(git rev-parse --symbolic-full-name HEAD@{upstream})"
    - name: Check origin branch name
    run: |
    if [[ ! ${{ steps.get-origin-branch.outputs.origin_branch }} =~ ^[PRJ|release|hotfix]/ ]]; then
    echo "Error: Origin branch name must start with PRJ/, release/, or hotfix/."
    exit 1
    fi
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Check bash
        run: | 
          echo $0  
          which bash   
      - name: Flutter version
        run: flutter --version                     
      - name: Run Lint
        run: flutter analyze --no-pub | grep -v 'TODO:'
      - name: Run tests 
        run: flutter test    

        