name: ci

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - 'dev/*'
      - 'staging/*'
      - 'main/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run Lint
        run: flutter analyze --no-pub --ignore "TODO:.*"
      - name: Run tests with coverage
        run: flutter test --coverage
      - name: Verify test coverage
        run: |
          pub global activate coverage
          coverage report --fail-under=80
