name: ci

on:
  push:
    branches:
      - feature/*
      - hotfix/*

  pull_quest:
      - dev/*
      - staging/*
      - main/*
jobs:
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'      
steps:
- uses: actions/checkout@v3
- uses: subosito/flutter-action@v2
  with:
    channel: 'stable'
- name: Get dependencies
  run: flutter pub get
- name: Run Lint
  run: flutter analyze --no-pub --ignore "TODO:.*"
- name: Run tests with coverage
  run: flutter test --coverage
- name: Verify test coverage
  run: |
    pub global activate coverage
    coverage combine
    coverage report --fail-under=80