name: ci

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - 'dev'
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Test version
        run: | 
          echo $0  
          which bash   
      - name: Flutter version
        run: flutter --version                     
      - name: Run Lint
        run: flutter analyze --no-pub | grep -v 'TODO:'
      - name: Run tests 
        run: flutter test    
      - name: Run tests with coverage
        if: github.event_name == 'pull_request'
        run: flutter test --coverage
      - name: Verify test coverage
        if: github.event_name == 'pull_request'
        run: |
          dart pub global activate coverage
          coverage report --fail-under=80
        shell: bash
          